//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AsmVisualStudio.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDC_NODROP                      106
#define IDB_RIBBON_MAIN                 112
#define IDB_RIBBON_BUTTONS              113
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDR_MAINFRAME                   128
#define IDR_MENU_TYPE                   130
#define IDI_ICON_PANEL_ARCHIVE          347
#define IDI_ICON_PANEL_FILES            348
#define IDI_ICON_PANEL_FIND             349
#define IDI_ICON_PANEL_MODULES          350
#define IDI_ICON_PANEL_OUTPUT           351
#define IDI_ICON_PANEL_TASK             352
#define IDB_BITMAP_TOOLBAR_ARCHIVE      356
#define IDB_BITMAP_TOOLBAR_FILE         357
#define IDB_BITMAP_TOOLBAR_MODULE       358
#define IDB_BITMAP_TOOLBAR_TASK         359
#define IDB_BITMAP_TOOLBAR_FIND         360
#define IDB_BITMAP_TREE_PANEL_FILES     361
#define IDB_BITMAP_TREE_PANEL_MODULES   362
#define IDB_BITMAP_ICONS_FILES          364
#define IDR_MENU_POPUP_OUTPUT           365
#define IDR_MENU_POPUP_FIND             366
#define IDR_MENU_POPUP_TASK             367
#define IDR_TOOLBAR_FIND                368
#define IDR_TOOLBAR_MODULES             370
#define IDR_TOOLBAR_FILES               372
#define IDR_TOOLBAR_ARCHIVE             374
#define IDR_TOOLBAR_TASK                376
#define IDR_TOOLBAR_FILE                378
#define IDR_TOOLBAR_MODULE              379
#define IDD_DIALOG_PROJECT_OPTIONS      382
#define IDD_DIALOG_BASE_OPTIONS         383
#define IDD_DIALOG_ORDER_PROJECTS       384
#define IDD_DIALOG_NEW_ELEMENT          386
#define IDD_DIALOG_GOTO_LINE            387
#define IDD_DIALOG_SHOW_UN_OPEN_PROJECT 388
#define IDD_DIALOG_SELECT_NAME          389
#define IDD_DIALOG_ADD_CONFIG           390
#define IDD_DIALOG_INPUT_NAME           391
#define IDD_DIALOG_FIND_REPLACE         392
#define IDR_MENU_POPUP_MODULES_ROOT     407
#define IDR_MENU_POPUP_MODULES_MODULE   408
#define IDR_MENU_POPUP_MODULES_EQU      411
#define IDR_MENU_POPUP_MODULES_ELEMENT  411
#define IDR_MENU_POPUP_FILES_ROOT       412
#define IDR_MENU_POPUP_FILES_FILE       413
#define IDR_MENU_POPUP_ARCHIVE_ROOT     414
#define IDR_MENU_POPUP_ARCHIVE_RESOURCE 415
#define IDR_MENU_POPUP_DOCUMENT         416
#define IDD_DIALOG_ARCHIVE_NEW          417
#define IDD_DIALOG_ARCHIVE_OPEN_RESOURCE 418
#define IDD_DIALOG_ARCHIVE_OPTIONS      420
#define IDC_CURSOR_DRAG                 423
#define ID_ADD_PROCEDURE                424
#define IDB_BITMAP_MENU_IMAGES          427
#define IDR_MENU_IMAGES                 428
#define IDR_MENU_POPUP_CODE_EDITOR      430
#define IDB_BITMAP_TOOLBAR_EDITOR       431
#define IDR_TOOLBAR_EDITOR              432
#define IDR_ASMVISUALSTUDIOTYPE         436
#define IDR_MENU_POPUP_MODULES_FOLDER   437
#define IDR_MENU2                       438
#define IDR_MENU_POPUP_FILES_FOLDER     438
#define IDB_BITMAP_RIBBON_LARGE         442
#define IDB_BITMAP2                     444
#define IDB_BITMAP_RIBBON_SMALL         444
#define IDI_ICON_PANEL_PROPERTIES       445
#define IDR_MENU1                       446
#define IDR_MENU_POPUP_ARCHIVE_FOLDER   446
#define IDD_DIALOG_ADD_MODULE_BLOCK     447
#define IDD_DIALOG_ADD_MODULE_PROCEDURE 447
#define IDD_DIALOG_ADD_MODULE_STRUCTURE 449
#define IDD_DIALOG2                     450
#define IDD_DIALOG_ADD_MODULE_EQU       450
#define IDD_DIALOG1                     452
#define IDD_DIALOG_EXCLUDE_BUILD        452
#define IDD_DIALOG_NEW_PROJECT          453
#define IDI_ICON_PROJECT                460
#define IDI_ICON_ARCHIVE                461
#define IDI_ICON_SOLUTION               462
#define IDI_ICON_ASM                    463
#define IDI_ICON2                       464
#define IDI_ICON_INC                    464
#define IDB_BITMAP1                     465
#define IDB_BITMAP_SPLASH               465
#define IDC_STATIC_LIST                 1000
#define IDC_COMBO1                      1001
#define IDC_COMBO_FIND_REPLACE_BAR      1001
#define IDC_COMBO_TYPE_BLOCK            1001
#define IDC_COMBO_TYPE_FIELD            1001
#define IDC_STATIC_FIND_REPLACE_BAR     1002
#define IDC_EDIT_NAME_BLOCK             1003
#define IDC_EDIT_VALUE_BLOCK            1004
#define IDC_EDIT_TYPE_NAME_BLOCK        1005
#define IDC_LIST_STRUCTURE_BLOCK        1006
#define IDC_EDIT_DIRECTIVE_USES_BLOCK   1007
#define IDC_EDIT_USES                   1007
#define IDC_STATIC_DIRECTIVE_USES_BLOCK 1008
#define IDC_BUTTON_FIND_ALL             1009
#define IDC_STATIC_VALUE_BLOCK          1010
#define IDC_BUTTON_ADD_FIELD            1011
#define ID_ADD_STRUCTURE                1012
#define IDC_BUTTON2                     1012
#define IDC_BUTTON_DEL_FIELD            1012
#define ID_ADD_EQU                      1013
#define ID_ADD_RESOURCE                 1014
#define IDC_EDIT_NAME_FIELD             1014
#define ID_ADD_NEW_RESOURCE             1015
#define IDC_LIST_FIELDS                 1015
#define IDC_EDIT_COMMENT                1016
#define IDC_EDIT_NAME_FIELD2            1017
#define IDC_EDIT_VALUE_FIELD            1017
#define IDC_EDIT_VALUE                  1018
#define IDC_BUTTON_DEL                  1019
#define IDC_EDIT1                       1019
#define IDC_EDIT_START_PARAMS           1019
#define IDC_COMBO_ACCESS                1020
#define IDC_STATIC_SOLUTION             1024
#define ID_PROPERTIES                   1030
#define ID_CONFIGURATIONS               1035
#define ID_PLATFORMS                    1036
#define ID_QUICK_FIND                   1037
#define ID_PANEL_STATUS_BAR             1063
#define ID_PANEL_OUTPUT                 1064
#define ID_PANEL_FIND                   1065
#define ID_PANEL_TASK                   1066
#define ID_PANEL_MODULES                1067
#define ID_PANEL_FILES                  1068
#define ID_PANEL_ARCHIVE                1069
#define IDC_BUTTON_ADD_CONFIG           1070
#define IDC_BUTTON_DEL_CONFIG           1071
#define IDC_COMBO_PLATFORM              1072
#define IDC_BUTTON_ADD_PLATFORM         1073
#define IDC_BUTTON_DEL_PLATFORM         1074
#define IDC_BUTTON_ORDER                1075
#define IDC_BUTTON_EXCLUDE              1076
#define IDC_COMBO_TRANS_LINK            1077
#define IDC_LIST_OPT                    1078
#define IDC_COMBO_CONFIG                1079
#define IDC_COMBO_WINDOW                1080
#define IDC_COMBO_FONT                  1081
#define IDC_COMBO_SIZE_FONT             1082
#define IDC_LIST_ELEMS                  1083
#define IDC_LIST_PARAMETERS             1084
#define IDC_LIST_KEYWORDS               1085
#define IDC_EDIT_NEW_KEYWORD            1086
#define IDC_BUTTON_ADD_KEYWORD          1087
#define IDC_BUTTON_DEL_KEYWORD          1088
#define IDC_STATIC_SAMPLE               1089
#define IDC_EDIT_DEF_FOLDER             1090
#define IDC_LIST_PROJECTS               1091
#define IDC_EDIT_DEF_FOLDER2            1091
#define IDC_EDIT_DEF_FOLDER_INCLUDE     1091
#define IDC_BUTTON_UP                   1092
#define IDC_EDIT_DEF_FOLDER_LIB         1092
#define IDC_BUTTON_DOWN                 1093
#define IDC_EDIT_LINE                   1094
#define IDC_LIST_TYPE                   1095
#define IDC_EDIT_NAME                   1096
#define IDC_EDIT_FOLDER                 1097
#define IDC_EDIT_NAME_SOLUTION          1098
#define IDC_STATIC_FOLDER               1099
#define IDC_STATIC_NAME_SOLUTION        1100
#define IDC_STATIC_TYPE                 1101
#define IDC_STATIC_NAME                 1102
#define IDC_COMBO_SELECT                1103
#define IDC_EDIT_NEW_NAME               1104
#define IDC_COMBO_CONFIGS               1105
#define IDC_LIST_LIST_PROJECTS          1106
#define IDC_COMBO_FIND                  1107
#define IDC_COMBO_REPLACE               1108
#define IDC_CHECK_CASE                  1109
#define IDC_CHECK_SELECTION             1110
#define IDC_CHECK_WORD                  1111
#define IDC_CHECK_HIDE_TEXT             1112
#define IDC_CHECK_ALL_FILES             1113
#define IDC_BUTTON_REPLACE              1114
#define IDC_STATIC_FIND                 1115
#define IDC_STATIC_REPLACE              1116
#define IDC_BUTTON_FIND_NEXT            1117
#define IDC_BUTTON_REPLACE_ALL          1118
#define IDC_BUTTON_BOOKMARK             1119
#define IDC_BUTTON_BOOKMARK_ALL         1120
#define ID_ARCHIVE_OPTIONS              1121
#define ID_ARCHIVE_OPTIMIZED            1124
#define ID_CREATE_LIST_RESOURCE         1125
#define ID_RESTORE_RESOURCE             1126
#define ID_SAVE_AS_TEXT_RESOURCE        1127
#define ID_ARCHIVE_CLOSE                1130
#define IDC_STATIC_PATH                 1131
#define IDC_EDIT_SIGNATURE              1132
#define IDC_EDIT_PATH                   1133
#define IDC_EDIT_PATH_LST               1134
#define IDC_COMBO_TYPE                  1135
#define IDC_CHECK_AVTO_BACKUP           1138
#define IDC_LIST_MODULES                1139
#define IDC_EDIT_PROG_ID                1140
#define IDC_BUTTON_ADD                  1141
#define IDC_BUTTON_REMOVE               1142
#define ID_COMBOBOX_GOTO_PROCEDURE      1143
#define ID_PANEL_PROPERTIES             1144
#define ID_ADD_DOCUMENT                 31913
#define ID_DELETE                       32804
#define ID_DOCUMENT_CLOSE               32829
#define ID_CLOSE_ALL_BUT_THIS           32831
#define ID_OPEN                         32836
#define ID_CID_CUT                      32845
#define ID_SET_STARTUP                  32847
#define ID_BUILD                        32850
#define ID_REMOVE_PROJECT               32856
#define ID_EXCLUDE_DOCUMENT             32862
#define ID_ACCELERATOR32865             32865
#define ID_32867                        32867
#define ID_POPUPMODULESMODULE_32871     32871
#define ID_REMOVE                       32900
#define ID_ARCHIVE_NEW                  32901
#define ID_ARCHIVE_OPEN                 32902
#define ID_RENAME                       32903
#define ID_ADD_NEW_RESOURCES            32904
#define ID_DOCUMENT_NEW                 32905
#define ID_DOCUMENT_OPEN                32906
#define ID_DOCUMENT_SAVE                32907
#define ID_DOCUMENT_SAVE_AS             32908
#define ID_SAVE_ALL                     32909
#define ID_CLOSE_ALL                    32910
#define ID_PROJECT_NEW                  32911
#define ID_PROJECT_OPEN                 32912
#define ID_ADD_PROJECT                  32913
#define ID_ADD_FOLDER                   32914
#define ID_ADD_NEW_DOCUMENT             32915
#define ID_ADD_NEW_PROJECT              32916
#define ID_REPLACE                      32917
#define ID_FIND                         32918
#define ID_REPLACE_IN_DOCUMENTS         32919
#define ID_FIND_IN_DOCUMENTS            32920
#define ID_GOTO_LOCATION                32921
#define ID_GOTO_NEXT_LOCATION           32922
#define ID_GOTO_PREV_LOCATION           32923
#define ID_CLEAR_CONTENT                32924
#define ID_BUILD_SOLUTION               32925
#define ID_REBUILD                      32926
#define ID_BUILD_PROJECT                32927
#define ID_EXECUTE                      32928
#define ID_OPTIONS                      32929
#define ID_PROJECT_OPTIONS              32930
#define ID_BOOKMARK_SET                 32931
#define ID_BOOKMARK_DELETE              32932
#define ID_BOOKMARK_ACTIVATED           32933
#define ID_BOOKMARK_DEACTIVATED         32934
#define ID_BOOKMARK_NEXT                32935
#define ID_BOOKMARK_PREV                32936
#define ID_SELECT_ALL                   32937
#define ID_UNDO                         32938
#define ID_REDO                         32939
#define ID_COPY                         32940
#define ID_CUT                          32941
#define ID_PASTE                        32942
#define ID_TASK_ERRORS                  32943
#define ID_TASK_WARNINGS                32944
#define ID_TASK_INFORMATIONS            32945
#define ID_BOOKMARK_ACTIVATED_ALL       32946
#define ID_BOOKMARK_DEACTIVATED_ALL     32947
#define ID_EXPAND_ALL                   32948
#define ID_COLLAPSE_ALL                 32949
#define ID_FORMAT_TEXT                  32950
#define ID_32951                        32951
#define ID_POPUPARCHIVEROOT_32952       32952
#define ID_POPUPARCHIVEROOT_32953       32953
#define ID_32954                        32954
#define ID_BOOKMARK_DELETE_ALL          32955

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        466
#define _APS_NEXT_COMMAND_VALUE         32956
#define _APS_NEXT_CONTROL_VALUE         1025
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
